[package]
name = "asio_jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asio-sys = "0.2.1"
cpal = { version = "0.15.2", features = ["asio", "asio-sys"] }
anyhow = "1.0.79"
